@startuml

class PathAwayEntity
class LivingEntity

package client {
    class FlyingCreatureRenderer
    class EntrypointClient
}

package server {
    class ModCreature
    class MountableCreature
    class FlyingCreature 
    class RunningCreature
    class EntrypointServer
    class Dragon
}

MountableCreature <--- FlyingCreature
ModCreature <|-- MountableCreature
MountableCreature <|-- RunningCreature
PathAwayEntity <|-- ModCreature
EntrypointServer *-- FlyingCreature
EntrypointClient *-- FlyingCreatureRenderer
FlyingCreature <|-- Dragon
@enduml